### ISSUE TITLE
Enhancement: replace console.log commands with proper logging service

### ISSUE THREAD

**Issue by mbonig** [modern-mean/modern-mean-core#127]
the console.log commands are handy during dev but become stripped in prod and lose a lot of value. Having all logging go through a service can open up to a lot of useful functionality later.

**Comment by trainerbill** [comment]
@mbonig Are you asking for an angular service that does all the logging?  Maybe a core constant to set debug level and all logging goes through Logger.log()?  Only problem I see is having to inject the service everywhere.  Can you explain a little more in depth of what you would like to see?

**Comment by trainerbill** [comment]
Thoughts on:

backend:  https://github.com/winstonjs/winston
Can make it configurable in the files as well as environment variables

frontend:  https://docs.angularjs.org/api/ng/provider/$logProvider
For the frontend I would probably just use the standard $log and have a constant to toggle on and off debug.  Unfortunately there isn't a way to turn the other logging off unless I make a decorator to just make the function return true if the others are disabled.

**Comment by mbonig** [comment]
Yes, I was thinking an angular service that would abstract the actually logging mechanism. For now it could simply log to the console (with an optional flag to do that at all, e.g. in production). 

Use case:

By default the 'modern-mean logger' is used, which simply outputs all .log() methods to the console. That logger also has an option to not output anything (except .error() messages) when in product. I could then replace this entire logger with one that sends all logging messages to a backend service.

I would not expect there to be a backend implementation to this, at least not as a first run. The first run should simply abstract out the console.log calls so that later on it can be replaced easily.

**Comment by trainerbill** [comment]
@mbonig What are your thoughts on my client side implementation I described above?  I think I can make it work nicely with the default $log and an angular constant and a decorator.  Don't think I will need a new service.  

I implemented winston on the server side.  The PR is larger than I wanted as I updated all the tests on the same PR...  But now you can specify log levels on the server side.  Its nice cause the test tasks now don't have any logs!

https://github.com/modern-mean/modern-mean-core/pull/136

**Comment by mbonig** [comment]
Using the existing $log would be great. Hadn't realized they already provided it!

**Comment by trainerbill** [comment]
Server side implemented with https://github.com/modern-mean/modern-mean-core/pull/136

will work on client side next

**Comment by mbonig** [comment]
Looks good! Always +1 when a commit includes removing a lot of code =-}

**Comment by trainerbill** [comment]
@mbonig Client side is done.

https://github.com/modern-mean/modern-mean-core/blob/master/docs/logging.md

Thoughts?

**Comment by mbonig** [comment]
Looks great, wouldn't add anything.
