### ISSUE TITLE
(discussion) Gulp Strip Debug

### ISSUE THREAD

**Issue by trainerbill** [modern-mean/modern-mean-core#2]
@siteshackinc Want your opinion on this.  Was shot down by MEAN contribs.  I want to add some strategic console.log() throughout the app and strip them with gulp-debug-strip.  This would make running in dev mode output some generic messages.  Like on controller instatiation console.log('HeaderController::Init', vm)

So now you can see that the controller is inited and the variables in the controller.  I always have to add these kinds of statements and it would just be easiest to provide them and strip them on production build.  Thoughts?

**Comment by siteshackinc** [comment]
@trainerbill definitely interested in seeing this for development mode as well.
