### ISSUE TITLE
feat(user) Rework all forms

### ISSUE THREAD

**Issue by trainerbill** [modern-mean/modern-mean-core#66]
Rework the forms for signin, signup, edit, password change to do client side validation etc.  

For all the forms we should be setting ng-disabled="vm.form.$invalid" so that the buttons aren't clickable until the form is valid

Couple things I saw:
1.  sign in -  no error message on an invalid login.
2.  Sign up -  no need for the error message under the buttons since it shows up on the fields

**Comment by trainerbill** [comment]
This is what happens when I submit the password changed form:

![image](https://cloud.githubusercontent.com/assets/3578259/13436047/ff6e63ce-dfa2-11e5-8d72-0d9a3ef6cb33.png)

You need to set the form back to pristine and display a better message.  Can barely tell that the password change was successful

**Comment by siteshackinc** [comment]
This was updated with #87 and #86

**Comment by siteshackinc** [comment]
Close issue?
